name: Deploy

on:
  pull_request:
    paths:
      - 'deployment/**.tf'
      - 'src/**.js'
  push:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Deploy
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use branch workspace
        uses: dflook/terraform-new-workspace@v1
        with:
          path: deployment
          workspace: ${{ github.head_ref }}

      - name: Terraform Apply
        uses: dflook/terraform-apply@v1
        with:
          path: deployment
          workspace: ${{ github.head_ref }}
          auto_approve: true
